language: python

stages:
    - test
    - coverage
    
install:
    - pip install -r requirements.txt
script:
    - python -m unittest tests

jobs:
    include:
        - python: 3.5
        - stage: coverage
          python: 3.5
          script:
            - coverage run --source=ConfigEnv -m unittest tests
          after_success:
            - coverage report -m
            - coveralls
